# Generated by Django 3.1.7 on 2021-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='wtime',
            field=models.IntegerField(default=9),
        ),
    ]
