# Generated by Django 3.1.7 on 2021-04-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_content_wtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='wtime',
            new_name='wakeup',
        ),
    ]
